In [ ]:
import pandas as pd

In [13]:
df_zover = pd.read_excel('../ZOVER_all_bat_viruses.xlsx', header=1)
df_zover

,SampleName,Host,CollectionDate,Country,Province,City,SampleDetails,BioProject,BioSample
0,Bat1,Artibeus lituratus,2007-10-05 00:00:00,Brazil,Sao Paulo,Valparaiso,Kidney,PRJNA557656,SAMN12405593
1,Bat2,Carollia perspicillata,2007-10-19 00:00:00,Brazil,Sao Paulo,Aracatuba,Liver,PRJNA557656,SAMN12405594
2,Bat3,Carollia perspicillata,2007-10-19 00:00:00,Brazil,Sao Paulo,Aracatuba,Kidney,PRJNA557656,SAMN12405595
3,Bat4,Glossophaga soricina,2007-10-19 00:00:00,Brazil,Sao Paulo,Aracatuba,Liver,PRJNA557656,SAMN12405596
4,Bat5,Glossophaga soricina,2007-10-19 00:00:00,Brazil,Sao Paulo,Aracatuba,Kidney,PRJNA557656,SAMN12405597
...,...,...,...,...,...,...,...,...,...
2967,Rt22QT161,Rhinolophus thomasi,2022-11-05 00:00:00,Vietnam,Quang Tri,ND,Feces,PRJNA1025946,SAMN37730889
2968,Rt22QT178,Rhinolophus thomasi,2022-11-05 00:00:00,Vietnam,Quang Tri,ND,Feces,PRJNA1025946,SAMN37730890
2969,Rt22QB8,Rhinolophus thomasi,2022-11-07 00:00:00,Vietnam,Quang Binh,ND,Feces,PRJNA1025946,SAMN37730872
2970,Rt22QB78,Rhinolophus thomasi,2022-11-10 00:00:00,Vietnam,Quang Binh,ND,Feces,PRJNA1025946,SAMN37730871
2971,Table saved from ZOVER [Wed Apr 01 2026],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_our = pd.read_csv('../sra_filtered_no_16S.csv', index_col=False)
df_our

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,Bytes,Center Name,Consent,DATASTORE filetype,...,env_package,experimental_factor,feature,identified_by,label,material,sample_ID,Host_Diet,organism,rel_to_oxygen
0,SRR868695,WGS,168,32700916,PRJNA203532,SAMN02147246,24426068,UNIVERSITY OF TURKU,public,"fastq,run.zq,sra",...,MIGS/MIMS/MIMARKS.host-associated,NaN,sea coast,NaN,bat-fin-2018,feces,NaN,insectivorous,NaN,NaN
1,SRR975462,OTHER,200,1112399600,PRJNA218570,SAMN02351598,742222275,INSTITUTE OF MILITARY VETERINARY,public,"fastq,sra",...,MIGS/MIMS/MIMARKS.host-associated,NaN,feces,NaN,NaN,feces,NaN,NaN,NaN,NaN
2,SRR6202122,WGS,202,18066072,PRJNA415003,SAMN07811889,9331475,BGI,public,"fastq,run.zq,sra",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SRR6202123,WGS,202,5645294,PRJNA415003,SAMN07811890,3525641,BGI,public,"fastq,run.zq,sra",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SRR6202124,WGS,202,6025458,PRJNA415003,SAMN07811891,3733079,BGI,public,"fastq,run.zq,sra",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153,ERR15951205,WGS,258,37874548118,PRJEB103765,SAMEA120589895,11473741804,QUADRAM INSTITUTE BIOSCIENCE,public,"sra,run.zq,fastq",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1154,ERR15951206,WGS,275,57310186414,PRJEB103765,SAMEA120589896,17777169612,QUADRAM INSTITUTE BIOSCIENCE,public,"run.zq,fastq,sra",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1155,ERR15951207,WGS,279,67460067788,PRJEB103765,SAMEA120589897,20797734971,QUADRAM INSTITUTE BIOSCIENCE,public,"run.zq,fastq,sra",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1156,SRR37069663,WGS,7864,1978643193,PRJNA1417558,SAMN54999376,622989701,JILIN AGRICULTURAL UNIVERSITY,public,"bam,sra",...,NaN,NaN,NaN,Jilin Provincial Key Laboratory of Animal Reso...,NaN,NaN,NaN,NaN,NaN,NaN
1157,SRR37069664,WGS,299,1974358067,PRJNA1417558,SAMN54999376,581263048,JILIN AGRICULTURAL UNIVERSITY,public,"sra,run.zq,fastq",...,NaN,NaN,NaN,Jilin Provincial Key Laboratory of Animal Reso...,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
matching_rows = df_our[df_our['BioSample'].isin(df_zover['BioSample'])]
matching_rows

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,Bytes,Center Name,Consent,DATASTORE filetype,...,env_package,experimental_factor,feature,identified_by,label,material,sample_ID,Host_Diet,organism,rel_to_oxygen
296,SRR15526222,WGS,413,6845308016,PRJNA755866,SAMN20860462,3139328791,CENTRAL RESEARCH INSTITUTE OF EPIDEMIOLOGY,public,"sra,fastq,run.zq",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,SRR15533060,WGS,426,5120782455,PRJNA755866,SAMN20865445,2374890584,CENTRAL RESEARCH INSTITUTE OF EPIDEMIOLOGY,public,"sra,run.zq,fastq",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,SRR15533116,WGS,420,4929550965,PRJNA755866,SAMN20865544,2287567394,CENTRAL RESEARCH INSTITUTE OF EPIDEMIOLOGY,public,"fastq,run.zq,sra",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,SRR15534018,WGS,390,4985418901,PRJNA755866,SAMN20866611,2296261435,CENTRAL RESEARCH INSTITUTE OF EPIDEMIOLOGY,public,"sra,fastq,run.zq",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,SRR15508011,WGS,361,3401885563,PRJNA755866,SAMN20845764,1685174259,CENTRAL RESEARCH INSTITUTE OF EPIDEMIOLOGY,public,"fastq,run.zq,sra",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
929,SRR19115556,OTHER,302,9366874582,PRJNA835632,SAMN28106605,2903091072,UNIVERSITY OF ZURICH (UZH),public,"fastq,sra,run.zq",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
930,SRR19115557,OTHER,302,6457390274,PRJNA835632,SAMN28106604,1980296837,UNIVERSITY OF ZURICH (UZH),public,"sra,fastq,run.zq",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
931,SRR19115558,OTHER,302,9868157738,PRJNA835632,SAMN28106603,3075462937,UNIVERSITY OF ZURICH (UZH),public,"run.zq,fastq,sra",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
932,SRR19115559,OTHER,302,4421956480,PRJNA835632,SAMN28106602,1378571615,UNIVERSITY OF ZURICH (UZH),public,"sra,fastq,run.zq",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
933,SRR19115560,OTHER,302,3753638634,PRJNA835632,SAMN28106601,1172516442,UNIVERSITY OF ZURICH (UZH),public,"run.zq,sra,fastq",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
matching_rows.to_csv('matching.csv')

In [29]:
not_matching_rows = df_our[~df_our['BioSample'].isin(df_zover['BioSample'])]
not_matching_rows['Collection_Date'].value_counts().to_csv('not_matched_dates.csv')

In [30]:
not_matching_rows.to_csv('not_matching.csv')

In [16]:
df_matches = pd.DataFrame()

In [18]:
df_matches['Matches'] = df_our['BioSample'].isin(df_zover['BioSample'])

In [21]:
df_matches['Project'] = df_our['BioProject'].isin(df_zover['BioProject'])

In [20]:
df_matches['Matches'].value_counts()

Matches
False    827
True     331
Name: count, dtype: int64

In [23]:
df_matches['Project'].value_counts()

Project
False    801
True     357
Name: count, dtype: int64

In [22]:
df_matches

      Matches  Project
0       False    False
1       False    False
2       False    False
3       False    False
4       False    False
...       ...      ...
1153    False    False
1154    False    False
1155    False    False
1156    False    False
1157    False    False

[1158 rows x 2 columns]