In [1]:
import pandas as pd

In [13]:
df1 = pd.read_excel("../diamond_best_hits_our_profiles.xlsx")
df2 = pd.read_excel("../diamond_best_hits_not_our_profiles.xlsx")

In [24]:
df1['compare_key'] = df1['qseqid'].str.split('|').str[-1].str.split('/').str[1:4].str.join('/')
df2['compare_key'] = df2['qseqid'].str.split('|').str[-1].str.split('/').str[1:4].str.join('/')

df1_only = df1[~df1['compare_key'].isin(df2['compare_key'])]
df2_only = df2[~df2['compare_key'].isin(df1['compare_key'])]

non_matching_rows = pd.concat([df1_only, df2_only])

non_matching_rows

,qseqid,sseqid,pident,align_len,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore,qlen,slen,qcovhsp,scovhsp,stitle,compare_key
3,SRR19115554|k141_38826/Hepatovirus/9406/4405-3...,NP_851403.1,70.2,1976,529,9,9037,3131,11,1933,0.000000,2738.0,9406,1933,62.8,99.5,NP_851403.1 non-structural polyprotein [Kashmi...,Hepatovirus/9406/4405-3142
7,SRR19115554|k141_5601/Parechovirus/5445/1959-2...,NP_851403.1,67.8,1656,473,8,498,5444,11,1613,0.000000,2189.0,5445,1933,90.9,82.9,NP_851403.1 non-structural polyprotein [Kashmi...,Parechovirus/5445/1959-2604
10,SRR19115554|k141_25830/Crohivirus/8097/1107-74...,YP_009407943.1,99.6,1078,4,0,3234,1,1,1078,0.000000,2138.0,8097,2145,39.9,50.3,"YP_009407943.1 RNA-dependent RNA polymerase, p...",Crohivirus/8097/1107-741
12,SRR19115554|k141_58113/Kobuvirus/3706/2050-895...,NP_066241.1,94.5,1091,58,2,3350,84,1,1091,0.000000,2035.0,3706,1906,88.2,57.2,NP_066241.1 replicase polyprotein [Acute bee p...,Kobuvirus/3706/2050-895
15,SRR19115554|k141_51339/Astroviridae/5822/2399-...,YP_009552769.1,68.0,1390,437,6,5787,1624,1,1384,0.000000,1886.0,5822,1761,71.5,78.6,YP_009552769.1 nonstructural polyprotein [Cule...,Astroviridae/5822/2399-1865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1956,SRR19115554|k141_36119/Potamipivirus/272/9-54/...,YP_009315867.1,93.8,16,1,0,4,51,1246,1261,0.000445,40.4,272,2830,2026-06-17 00:00:00,0.6,YP_009315867.1 polyprotein [Corey virus],Potamipivirus/272/9-54
1957,SRR33769988|k141_69481/Ampivirus/354/282-321/1...,YP_009701834.1,36.7,49,31,0,195,341,4,52,0.000843,40.4,354,269,41.5,2026-02-18 00:00:00,YP_009701834.1 GIY-YIG catalytic domain-contai...,Ampivirus/354/282-321
1962,SRR19115554|k141_26022/Potamipivirus/281/170-1...,YP_009315867.1,59.3,27,11,0,207,127,1235,1261,0.000675,40.0,281,2830,2026-08-28 00:00:00,1.0,YP_009315867.1 polyprotein [Corey virus],Potamipivirus/281/170-125
1965,SRR33769988|k141_132164/Ampivirus/303/63-24/1....,YP_009701834.1,36.7,49,31,0,151,5,4,52,0.000978,39.7,303,269,48.5,2026-02-18 00:00:00,YP_009701834.1 GIY-YIG catalytic domain-contai...,Ampivirus/303/63-24
1969,SRR33769988|k141_180754/Ampivirus/207/147-186/...,YP_009701834.1,36.7,49,31,0,59,205,4,52,0.000857,38.5,207,269,71.0,2026-02-18 00:00:00,YP_009701834.1 GIY-YIG catalytic domain-contai...,Ampivirus/207/147-186

In [25]:
df1_only

,qseqid,sseqid,pident,align_len,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore,qlen,slen,qcovhsp,scovhsp,stitle,compare_key
3,SRR19115554|k141_38826/Hepatovirus/9406/4405-3...,NP_851403.1,70.2,1976,529,9,9037,3131,11,1933,0.000000,2738.0,9406,1933,62.8,99.5,NP_851403.1 non-structural polyprotein [Kashmi...,Hepatovirus/9406/4405-3142
7,SRR19115554|k141_5601/Parechovirus/5445/1959-2...,NP_851403.1,67.8,1656,473,8,498,5444,11,1613,0.000000,2189.0,5445,1933,90.9,82.9,NP_851403.1 non-structural polyprotein [Kashmi...,Parechovirus/5445/1959-2604
10,SRR19115554|k141_25830/Crohivirus/8097/1107-74...,YP_009407943.1,99.6,1078,4,0,3234,1,1,1078,0.000000,2138.0,8097,2145,39.9,50.3,"YP_009407943.1 RNA-dependent RNA polymerase, p...",Crohivirus/8097/1107-741
12,SRR19115554|k141_58113/Kobuvirus/3706/2050-895...,NP_066241.1,94.5,1091,58,2,3350,84,1,1091,0.000000,2035.0,3706,1906,88.2,57.2,NP_066241.1 replicase polyprotein [Acute bee p...,Kobuvirus/3706/2050-895
15,SRR19115554|k141_51339/Astroviridae/5822/2399-...,YP_009552769.1,68.0,1390,437,6,5787,1624,1,1384,0.000000,1886.0,5822,1761,71.5,78.6,YP_009552769.1 nonstructural polyprotein [Cule...,Astroviridae/5822/2399-1865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1953,SRR33769988|k141_5118/Caliciviridae/439/204-24...,YP_010778573.1,26.0,146,100,4,21,437,250,394,0.000332,42.7,439,849,95.0,2026-01-17 00:00:00,YP_010778573.1 putative Non-LTR retrotransposo...,Caliciviridae/439/204-240
1957,SRR30793080|k141_38541/Astroviridae/346/105-30...,YP_002117594.1,39.1,69,41,1,116,322,57,124,0.000128,42.7,346,299,59.8,2026-07-22 00:00:00,YP_002117594.1 protease [Rhizobium phage 16-3],Astroviridae/346/105-300
1991,SRR19115554|k141_7234/Potamipivirus/338/275-21...,YP_009281134.1,34.6,52,34,0,174,329,32,83,0.000570,40.8,338,332,46.2,2026-07-15 00:00:00,YP_009281134.1 Sak4-like ssDNA annealing prote...,Potamipivirus/338/275-215
1992,SRR33769988|k141_161446/Livupivirus/320/204-27...,YP_073558.1,2026-03-31 00:00:00,67,46,0,216,16,134,200,0.000507,40.8,320,483,62.8,2026-09-13 00:00:00,YP_073558.1 RNA-dependent DNA polymerase [lymp...,Livupivirus/320/204-276
1998,SRR19115554|k141_7907/Potamipivirus/219/9-54/2...,YP_009315867.1,93.8,16,1,0,4,51,1246,1261,0.000236,40.4,219,2830,2026-09-21 00:00:00,0.6,YP_009315867.1 polyprotein [Corey virus],Potamipivirus/219/9-54

In [32]:
df_filtered = df1_only[df1_only['compare_key'].str.split('/').str[0].isin(['Astroviridae', 'Parechovirus', 'Kobuvirus', 'Mamastrovirus'])]
df_filtered.to_csv('new_hits_with_our_profiles.csv')

In [30]:
df_filtered = df2_only[df2_only['compare_key'].str.split('/').str[0].isin(['Astroviridae', 'Parechovirus', 'Kobuvirus', 'Mamastrovirus'])]
df_filtered

,qseqid,sseqid,pident,align_len,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore,qlen,slen,qcovhsp,scovhsp,stitle,compare_key
58,SRR14381429|k141_5240/Astroviridae/6707/2483-3...,YP_009505809.1,69.4,758,214,9,2377,137,48,798,0.000000e+00,1010.0,6707,800,33.4,93.9,YP_009505809.1 capsid protein precursor [Bat a...,Astroviridae/6707/2483-329
61,SRR14381429|k141_7260/Astroviridae/2484/72-204...,YP_009505809.1,68.0,756,230,8,160,2400,46,798,0.000000e+00,999.0,2484,800,90.2,94.1,YP_009505809.1 capsid protein precursor [Bat a...,Astroviridae/2484/72-2040
69,SRR14381429|k141_23718/Astroviridae/4882/2467-...,YP_009505809.1,65.3,760,243,11,2370,130,46,797,0.000000e+00,942.0,4882,800,45.9,94.0,YP_009505809.1 capsid protein precursor [Bat a...,Astroviridae/4882/2467-301
88,SRR14381429|k141_2056/Astroviridae/1749/1713-6...,YP_009505809.1,72.2,543,135,9,1611,19,47,585,1.890000e-270,761.0,1749,800,91.1,67.4,YP_009505809.1 capsid protein precursor [Bat a...,Astroviridae/1749/1713-6
96,SRR14381429|k141_6113/Astroviridae/3436/1008-3...,YP_009664789.1,51.9,769,300,16,1137,3239,73,839,2.390000e-248,728.0,3436,850,61.2,90.2,YP_009664789.1 capsid protein precursor [Mamas...,Astroviridae/3436/1008-3096
97,SRR19115554|k141_39351/Astroviridae/1226/942-1...,YP_009164038.1,84.1,402,64,0,18,1223,26,427,4.520000e-262,723.0,1226,539,98.4,74.6,YP_009164038.1 RNA-dependent RNA polymerase [V...,Astroviridae/1226/942-1050
120,SRR19115554|k141_58024/Astroviridae/5601/2169-...,YP_009664783.1,62.8,468,174,0,3593,2190,1,468,9.770000e-214,644.0,5601,470,2026-01-25 00:00:00,99.6,"YP_009664783.1 non-structural polyprotein 1AB,...",Astroviridae/5601/2169-93
131,SRR14381429|k141_12544/Mamastrovirus/1485/1260...,YP_009664790.1,67.5,428,138,1,1285,2,1,427,3.650000e-218,614.0,1485,522,86.5,81.8,"YP_009664790.1 non-structural polyprotein 1AB,...",Mamastrovirus/1485/1260-6
144,SRR14381429|k141_32170/Mamastrovirus/1985/1640...,YP_009664783.1,57.7,471,197,2,1496,84,1,469,1.790000e-201,577.0,1985,470,71.2,99.8,"YP_009664783.1 non-structural polyprotein 1AB,...",Mamastrovirus/1985/1640-83
165,SRR19115554|k141_56778/Parechovirus/2838/1527-...,YP_009337376.1,57.2,437,184,3,1433,2740,4,438,1.360000e-179,530.0,2838,441,46.1,98.6,YP_009337376.1 hypothetical protein 2 [Wenzhou...,Parechovirus/2838/1527-2427
229,SRR19115554|k141_31774/Parechovirus/801/705-48...,YP_009342337.1,83.1,261,44,0,783,1,176,436,2.870000e-149,464.0,801,2914,97.8,9.0,YP_009342337.1 hypothetical protein [Wuhan fly...,Parechovirus/801/705-48
276,SRR19115554|k141_10122/Parechovirus/1490/453-8...,YP_009143313.1,43.5,481,265,5,9,1439,80,557,4.340000e-133,402.0,1490,659,96.0,72.5,YP_009143313.1 RNA-dependent RNA polymerase [C...,Parechovirus/1490/453-861
331,SRR14381429|k141_17671/Mamastrovirus/2954/2339...,NP_795334.1,32.5,841,489,18,2793,388,71,871,1.580000e-105,352.0,2954,874,81.4,91.6,NP_795334.1 putative serine protase [Mamastrov...,Mamastrovirus/2954/2339-371
339,SRR19115554|k141_17430/Parechovirus/1863/1089-...,YP_009330098.1,58.2,285,117,2,1004,1858,1,283,4.050000e-112,342.0,1863,353,45.9,80.2,YP_009330098.1 hypothetical protein 3 [Hubei s...,Parechovirus/1863/1089-1740
365,SRR19115554|k141_24184/Parechovirus/2382/732-7...,YP_009337376.1,43.6,346,190,2,1035,1,17,358,1.970000e-99,318.0,2382,441,43.5,77.6,YP_009337376.1 hypothetical protein 2 [Wenzhou...,Parechovirus/2382/732-72
409,SRR14381429|k141_11209/Mamastrovirus/545/536-2...,YP_009664790.1,70.0,180,54,0,542,3,230,409,1.540000e-93,284.0,545,522,99.1,34.5,"YP_009664790.1 non-structural polyprotein 1AB,...",Mamastrovirus/545/536-2
429,SRR14381429|k141_31103/Astroviridae/2061/2058-...,YP_003275953.1,49.2,301,139,6,2060,1176,102,394,4.160000e-79,270.0,2061,731,42.9,40.1,YP_003275953.1 capsid [HMO Astrovirus A],Astroviridae/2061/2058-375
432,SRR14381429|k141_23939/Parechovirus/662/221-44...,YP_007419077.1,62.8,199,73,1,662,66,235,432,5.260000e-86,268.0,662,603,90.2,32.8,YP_007419077.1 RNA-dependent RNA polymerase [R...,Parechovirus/662/221-44
467,SRR14381429|k141_19378/Mamastrovirus/526/3-522...,YP_009664787.1,66.7,171,57,0,1,513,614,784,1.230000e-78,252.0,526,816,97.5,21.0,"YP_009664787.1 polyprotein 1AB, partial [Mamas...",Mamastrovirus/526/3-522
476,SRR14381429|k141_1235/Mamastrovirus/1794/1722-...,YP_009047247.1,32.3,585,369,11,1732,38,13,590,8.000000e-72,250.0,1794,861,94.5,67.1,YP_009047247.1 ORF1A nonstructural polyprotein...,Mamastrovirus/1794/1722-21
497,SRR30793080|k141_94865/Astroviridae/5506/4075-...,YP_009831980.1,63.0,181,58,2,3107,2592,1,181,1.170000e-68,236.0,5506,288,2026-04-09 00:00:00,62.8,YP_009831980.1 endolysin [Aeribacillus phage A...,Astroviridae/5506/4075-3628
536,SRR14381429|k141_16330/Mamastrovirus/1116/1092...,YP_003090287.1,36.3,347,216,4,1088,63,253,599,1.090000e-63,221.0,1116,886,91.9,39.2,YP_003090287.1 non-structural protein 1a [Astr...,Mamastrovirus/1116/1092-12
596,SRR14381429|k141_12048/Astroviridae/413/177-33...,YP_009664790.1,68.6,137,43,0,1,411,245,381,1.550000e-63,204.0,413,522,99.5,2026-02-26 00:00:00,"YP_009664790.1 non-structural polyprotein 1AB,...",Astroviridae/413/177-333
642,SRR19115554|k141_18106/Parechovirus/282/39-78/...,YP_009158862.1,90.4,94,9,0,1,282,183,276,9.980000e-62,191.0,282,276,100.0,34.1,YP_009158862.1 replication-associated protein ...,Parechovirus/282/39-78
644,SRR14381429|k141_11222/Astroviridae/394/346-18...,YP_009664787.1,68.5,130,41,0,393,4,577,706,6.360000e-57,191.0,394,816,99.0,2026-09-15 00:00:00,"YP_009664787.1 polyprotein 1AB, partial [Mamas...",Astroviridae/394/346-181
655,SRR19115554|k141_44101/Parechovirus/2416/1359-...,YP_009336787.1,28.0,572,377,12,623,2287,1534,2087,1.270000e-47,187.0,2416,3290,68.9,2026-08-16 00:00:00,YP_009336787.1 hypothetical protein [Wenzhou p...,Parechovirus/2416/1359-2409
658,SRR14381429|k141_35057/Astroviridae/349/346-26...,YP_009664790.1,70.7,116,34,0,349,2,403,518,4.150000e-57,187.0,349,522,99.7,2026-02-22 00:00:00,"YP_009664790.1 non-structural polyprotein 1AB,...",Astroviridae/349/346-265
665,SRR19115554|k141_19387/Parechovirus/282/201-24...,YP_009158862.1,90.3,93,9,0,3,281,129,221,8.880000e-60,186.0,282,276,98.9,33.7,YP_009158862.1 replication-associated protein ...,Parechovirus/282/201-240
678,SRR14381429|k141_28513/Astroviridae/373/159-33...,YP_009664790.1,70.2,121,36,0,10,372,59,179,8.620000e-56,184.0,373,522,97.3,2026-02-23 00:00:00,"YP_009664790.1 non-structural polyprotein 1AB,...",Astroviridae/373/159-336
694,SRR14381429|k141_14411/Astroviridae/320/72-246...,YP_009664790.1,75.5,106,26,0,1,318,162,267,4.450000e-55,181.0,320,522,99.4,2026-03-20 00:00:00,"YP_009664790.1 non-structural polyprotein 1AB,...",Astroviridae/320/72-246
706,SRR14381429|k141_25517/Mamastrovirus/412/15-41...,YP_009664787.1,58.4,137,57,0,1,411,299,435,1.770000e-52,179.0,412,816,99.8,2026-08-16 00:00:00,"YP_009664787.1 polyprotein 1AB, partial [Mamas...",Mamastrovirus/412/15-411
719,SRR14381429|k141_22494/Mamastrovirus/1016/36-1...,YP_004782205.1,35.1,345,193,9,4,1014,335,656,2.530000e-48,176.0,1016,849,99.5,37.9,YP_004782205.1 ORF1a [Mouse astrovirus M-52/US...,Mamastrovirus/1016/36-1014
721,SRR14381429|k141_33606/Mamastrovirus/427/27-42...,YP_009664787.1,60.0,135,54,0,21,425,289,423,1.330000e-50,174.0,427,816,94.8,2026-05-16 00:00:00,"YP_009664787.1 polyprotein 1AB, partial [Mamas...",Mamastrovirus/427/27-423
733,SRR14381429|k141_2179/Astroviridae/347/3-342/9...,YP_009505809.1,71.3,115,33,0,1,345,220,334,1.070000e-49,171.0,347,800,99.4,2026-04-14 00:00:00,YP_009505809.1 capsid protein precursor [Bat a...,Astroviridae/347/3-342
747,SRR19115554|k141_57772/Astroviridae/1147/48-11...,YP_009330096.1,39.4,226,135,2,36,710,137,361,7.580000e-46,167.0,1147,504,58.8,44.6,YP_009330096.1 hypothetical protein 1 [Hubei s...,Astroviridae/1147/48-111
757,SRR19115554|k141_14986/Parechovirus/836/833-49...,YP_009329985.1,52.8,144,68,0,834,403,1553,1696,2.130000e-45,166.0,836,1701,51.7,2026-05-08 00:00:00,YP_009329985.1 hypothetical protein 1 [Hubei p...,Parechovirus/836/833-491
768,SRR14381429|k141_35148/Astroviridae/463/9-420/...,YP_009505809.1,55.1,158,65,3,1,462,298,453,8.080000e-47,164.0,463,800,99.8,2026-05-19 00:00:00,YP_009505809.1 capsid protein precursor [Bat a...,Astroviridae/463/9-420
866,SRR14381429|k141_36079/Astroviridae/301/57-234...,YP_009664790.1,66.7,96,32,0,14,301,422,517,6.300000e-42,146.0,301,522,95.7,2026-04-18 00:00:00,"YP_009664790.1 non-structural polyprotein 1AB,...",Astroviridae/301/57-234
956,SRR14381429|k141_24874/Mamastrovirus/401/395-2...,YP_003090286.1,47.0,134,70,1,401,3,446,579,2.120000e-35,131.0,401,1394,99.5,2026-06-09 00:00:00,YP_003090286.1 non-structural protein 1ab [Ast...,Mamastrovirus/401/395-2
1008,SRR14381429|k141_22844/Astroviridae/427/421-67...,YP_009505809.1,48.6,146,64,3,427,2,351,489,1.390000e-32,124.0,427,800,99.8,2026-04-17 00:00:00,YP_009505809.1 capsid protein precursor [Bat a...,Astroviridae/427/421-67
1017,SRR19115554|k141_32519/Parechovirus/418/48-282...,YP_009417301.1,42.6,129,74,0,18,404,403,531,1.650000e-32,123.0,418,811,92.6,2026-09-15 00:00:00,YP_009417301.1 RdRp [Australian Anopheles toti...,Parechovirus/418/48-282
1036,SRR19115554|k141_19247/Parechovirus/306/276-27...,YP_009337003.1,54.2,107,42,1,305,6,160,266,1.950000e-32,121.0,306,2786,98.0,2026-08-03 00:00:00,YP_009337003.1 hypothetical protein [Hubei pic...,Parechovirus/306/276-27
1096,SRR14381429|k141_13525/Astroviridae/451/153-44...,YP_009505809.1,85.1,67,8,1,255,449,46,112,4.210000e-29,114.0,451,800,43.2,2026-04-08 00:00:00,YP_009505809.1 capsid protein precursor [Bat a...,Astroviridae/451/153-447
1102,SRR30793080|k141_56310/Astroviridae/1630/133-5...,YP_009199114.1,31.0,271,169,6,1339,566,18,283,8.610000e-27,113.0,1630,290,47.5,91.7,YP_009199114.1 integrase [Brevibacillus phage ...,Astroviridae/1630/133-58
1270,SRR14381429|k141_31459/Mamastrovirus/960/297-7...,YP_010804469.1,31.0,239,146,8,264,959,27,253,1.140000e-20,95.1,960,458,72.5,49.6,YP_010804469.1 hypothetical protein QKU58_gp06...,Mamastrovirus/960/297-711
1397,SRR14381429|k141_19524/Mamastrovirus/351/3-345...,YP_009664787.1,38.9,126,63,5,2,349,121,242,7.690000e-19,83.6,351,816,99.1,15.0,"YP_009664787.1 polyprotein 1AB, partial [Mamas...",Mamastrovirus/351/3-345
1449,SRR33769988|k141_379039/Astroviridae/543/117-1...,YP_009665762.1,32.9,143,90,3,419,9,190,332,3.480000e-16,78.6,543,799,75.7,2026-09-17 00:00:00,YP_009665762.1 19.5g1 protein [Bracoviriform i...,Astroviridae/543/117-162
1512,SRR14381429|k141_10392/Mamastrovirus/874/3-738...,YP_004782205.1,2026-06-27 00:00:00,250,157,8,2,700,21,263,9.460000e-13,71.6,874,849,80.0,2026-06-28 00:00:00,YP_004782205.1 ORF1a [Mouse astrovirus M-52/US...,Mamastrovirus/874/3-738
1560,SRR19115554|k141_14566/Astroviridae/534/30-519...,YP_010804469.1,37.7,159,82,7,64,534,38,181,5.290000e-12,66.2,534,458,88.2,31.4,YP_010804469.1 hypothetical protein QKU58_gp06...,Astroviridae/534/30-519
1588,SRR19115554|k141_55211/Astroviridae/2375/21-67...,YP_010804469.1,2026-01-28 00:00:00,288,166,12,248,1027,38,312,2.270000e-09,63.9,2375,458,32.8,60.0,YP_010804469.1 hypothetical protein QKU58_gp06...,Astroviridae/2375/21-675
1610,SRR14381429|k141_26004/Astroviridae/934/370-27...,YP_010804469.1,36.7,128,69,4,378,1,36,153,1.050000e-09,62.4,934,458,40.5,2026-08-25 00:00:00,YP_010804469.1 hypothetical protein QKU58_gp06...,Astroviridae/934/370-274
1619,SRR14381429|k141_2861/Astroviridae/482/473-368...,YP_009333547.1,34.0,100,58,1,482,183,1659,1750,1.580000e-10,61.6,482,1863,62.2,2026-09-04 00:00:00,YP_009333547.1 hypothetical protein 1 [Beihai ...,Astroviridae/482/473-368
1629,SRR33769988|k141_143440/Parechovirus/3291/72-1...,YP_009665762.1,2026-08-24 00:00:00,161,115,4,2092,1619,235,392,4.850000e-08,60.8,3291,799,2026-04-14 00:00:00,2026-08-19 00:00:00,YP_009665762.1 19.5g1 protein [Bracoviriform i...,Parechovirus/3291/72-117
1639,SRR14381429|k141_9829/Mamastrovirus/557/506-14...,YP_006905855.1,2026-07-26 00:00:00,176,125,1,540,25,215,390,9.660000e-10,60.1,557,886,92.6,2026-09-19 00:00:00,YP_006905855.1 ORF1a [Astrovirus VA4],Mamastrovirus/557/506-14
1662,SRR19115554|k141_1203/Mamastrovirus/638/527-17...,YP_007003831.1,37.0,92,58,0,494,219,80,171,5.810000e-09,58.5,638,844,43.3,2026-09-10 00:00:00,YP_007003831.1 ORF1a [Porcine astrovirus 3],Mamastrovirus/638/527-17
1703,SRR33769988|k141_251289/Astroviridae/205/133-8...,YP_009666308.1,39.4,66,40,0,200,3,791,856,6.500000e-10,55.8,205,1045,96.6,2026-03-06 00:00:00,"YP_009666308.1 Reverse Transcriptase, partial ...",Astroviridae/205/133-85
1804,SRR14381429|k141_16740/Mamastrovirus/398/374-1...,NP_059945.2,35.5,110,63,3,360,46,99,205,1.790000e-06,48.9,398,1351,79.1,2026-09-07 00:00:00,NP_059945.2 orf1ab polyprotein (orf1ab) [Mamas...,Mamastrovirus/398/374-143
1843,SRR14860657|k141_1674/Mamastrovirus/350/21-111...,YP_010079892.1,2026-03-29 00:00:00,58,41,0,6,179,215,272,5.720000e-06,46.6,350,280,49.7,2026-07-20 00:00:00,YP_010079892.1 exfoliative toxin A [Staphyloco...,Mamastrovirus/350/21-111
1909,SRR30793080|k141_84201/Mamastrovirus/346/69-33...,YP_002117594.1,39.1,69,41,1,116,322,57,124,1.280000e-04,42.7,346,299,59.8,2026-07-22 00:00:00,YP_002117594.1 protease [Rhizobium phage 16-3],Mamastrovirus/346/69-333