In [5]:
import pandas as pd

In [6]:
df_zover = pd.read_excel('ZOVER_bat_astroviruses.xlsx', header=1)
df_zover

,SampleName,Host,CollectionDate,Country,Province,City,SampleDetails,BioProject,BioSample
0,KSA_0412,Eidolon helvum,2012-10~2013-04,Saudi Arabia,Asir,Bisha,Rectal swab/fecal pellet,PRJNA487099,SAMN09873731
1,KSA_0430,unclassified Chiroptera,2012-10~2013-04,Saudi Arabia,Asir,Bisha,Rectal swab/fecal pellet,PRJNA487099,SAMN09873749
2,KSA_0435,Taphozous perforatus,2012-10~2013-04,Saudi Arabia,Asir,Bisha,Rectal swab/fecal pellet,PRJNA487099,SAMN09873753
3,130415_lane8,Miniopterus fuliginosus,2013,China,Guangdong,ND,Pharyngeal and anal swab,PRJNA171017,SAMN03761340
4,130601_lane8,Myotis ricketti,2013,China,Guangdong,ND,Pharyngeal and anal swab,PRJNA171017,SAMN03761350
...,...,...,...,...,...,...,...,...,...
149,L173.18,Myotis pilosus,2022-08,China,Guizhou,ND,Rectum,PRJNA901878,SAMN32394997
150,L177.18,Ia io,2022-08,China,Guizhou,ND,Rectum,PRJNA901878,SAMN32395001
151,P11,Myotis daubentonii,2022-08-03~2022-08-17,Spain,Lugo/Salamanca,Rabade/Navarredonda de la Rinconada,Feces,PRJNA1074704,SAMN39879841
152,Ra22QT106,Rhinolophus affinis,2022-11-03 00:00:00,Vietnam,Quang Tri,ND,Feces,PRJNA1025946,SAMN37730895
153,Table saved from ZOVER [Tue Apr 07 2026],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_our = pd.read_csv('filtered_table.csv', index_col=False)
df_our

D:\Users\User\AppData\Local\Temp\ipykernel_11880\2315709968.py:1: DtypeWarning: Columns (0: source_material_id, 1: Location_Province, 2: ArrayExpress-SPECIES, 3: common_name, 4: ENA-FIRST-PUBLIC, 5: ENA-LAST-UPDATE, 6: external_id, 7: INSDC_first_public, 8: INSDC_last_update, 9: sample_description, 10: Sample_Barcode, 11: ref_biomaterial, 12: collected_by, 13: tissue, 14: Broker_name, 15: env_biome, 16: env_feature, 17: env_material, 18: Biological_Replicate, 19: host_scientific_name, 20: lab_host, 21: specimen_voucher, 22: expected_source, 23: host_body_product, 24: host_tot_mass, 25: manuscript_id, 26: samp_capt_status, 27: samp_collect_device, 28: fasta_file (run), 29: sample_type, 30: sex, 31: BREED, 32: Cultivar, 33: dev_stage, 34: ecotype, 35: sub_species, 36: samp_size, 37: Library_ID, 38: rel_to_oxygen, 39: replicate, 40: SUBMISSION_TOOL (exp), 41: SUBMISSION_TOOL (run), 42: submission_tool, 43: SUBMISSION_TOOL_VERSION (exp), 44: SUBMISSION_TOOL_VERSION (run), 45: SUBMISSION_TOOL_VERSION, 46: genbank_accession, 47: sequencing_approach, 48: virus_enrich_app, 49: experimental_factor, 50: sample_ID, 51: specific_host, 52: altitude, 53: BIOME, 54: env_package, 55: feature, 56: Investigation_type, 57: Label, 58: material, 59: sample_comment) have mixed types. Specify dtype option on import or set low_memory=False.
  df_our = pd.read_csv('filtered_table.csv', index_col=False)

,Run,Assay Type,AvgSpotLen,Bases,BioSample,Bytes,Center Name,Consent,DATASTORE filetype,DATASTORE provider,...,additional_component_added_to_sample,altitude,BIOME,env_package,feature,Investigation_type,Label,material,sample_comment,spike_in_level_of_influenza_a_virus
0,SRR31363909,WGS,286,474453275,SAMN44728217,173166448,REDEEMERS UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SRR31363910,WGS,299,598547547,SAMN44728216,221765048,REDEEMERS UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SRR31363911,WGS,298,57040761,SAMN44727980,34122192,REDEEMERS UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SRR31363912,WGS,274,545825235,SAMN44727979,219057341,REDEEMERS UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SRR31363913,WGS,263,1442370106,SAMN44727972,539922913,REDEEMERS UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5480,ERR15951191,WGS,212,10740246317,SAMEA120589881,3365993450,QUADRAM INSTITUTE BIOSCIENCE,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5481,ERR15951193,WGS,280,59183488003,SAMEA120589883,17798921408,QUADRAM INSTITUTE BIOSCIENCE,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5482,ERR15951194,WGS,271,35140445635,SAMEA120589884,10911327171,QUADRAM INSTITUTE BIOSCIENCE,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5483,ERR15951203,WGS,274,6685169405,SAMEA120589893,2044166040,QUADRAM INSTITUTE BIOSCIENCE,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5484,SRR36330079,RNA-Seq,265,20195,SAMN53697127,92144,FEDERAL UNIVERSITY OF SAO PAULO,public,"bam,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
matching_rows = df_our[df_our['BioSample'].isin(df_zover['BioSample'])]
matching_rows

,Run,Assay Type,AvgSpotLen,Bases,BioSample,Bytes,Center Name,Consent,DATASTORE filetype,DATASTORE provider,...,additional_component_added_to_sample,altitude,BIOME,env_package,feature,Investigation_type,Label,material,sample_comment,spike_in_level_of_influenza_a_virus
100,SRR27912332,WGS,298,1791628746,SAMN39879841,756283095,UNIVERSITAT DE VALENCIA,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,SRR22936602,WGS,300,12457547100,SAMN32394822,3967403963,SOUTH CHINA AGRICULTURAL UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,SRR22936710,WGS,300,12308733300,SAMN32394898,4015418116,SOUTH CHINA AGRICULTURAL UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,SRR22936796,WGS,300,32661453600,SAMN32394997,10730387949,SOUTH CHINA AGRICULTURAL UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,SRR22936808,WGS,300,22326472500,SAMN32394986,7399477101,SOUTH CHINA AGRICULTURAL UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4538,SRR28250713,RNA-Seq,295,14969290933,SAMN40259440,9899035905,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4617,SRR28250862,RNA-Seq,297,628042915,SAMN40258967,394929857,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4643,SRR28250888,RNA-Seq,299,8446609858,SAMN40258880,5532514188,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4699,SRR28250944,RNA-Seq,296,1660832541,SAMN40259089,1055677929,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4725,SRR28250970,RNA-Seq,297,8606908315,SAMN40259126,5418286293,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
matching_rows.to_csv('matching.csv')

In [29]:
not_matching_rows = df_our[~df_our['BioSample'].isin(df_zover['BioSample'])]
not_matching_rows['Collection_Date'].value_counts().to_csv('not_matched_dates.csv')

In [30]:
not_matching_rows.to_csv('not_matching.csv')

In [16]:
df_matches = pd.DataFrame()

In [18]:
df_matches['Matches'] = df_our['BioSample'].isin(df_zover['BioSample'])

In [21]:
df_matches['Project'] = df_our['BioProject'].isin(df_zover['BioProject'])

In [20]:
df_matches['Matches'].value_counts()

Matches
False    827
True     331
Name: count, dtype: int64

In [23]:
df_matches['Project'].value_counts()

Project
False    801
True     357
Name: count, dtype: int64

In [22]:
df_matches

      Matches  Project
0       False    False
1       False    False
2       False    False
3       False    False
4       False    False
...       ...      ...
1153    False    False
1154    False    False
1155    False    False
1156    False    False
1157    False    False

[1158 rows x 2 columns]