In [1]:
import pandas as pd

In [8]:
df_zover = pd.read_excel('ZOVER_all_bat_viruses.xlsx', header=1)
df_zover

,SampleName,Host,CollectionDate,Country,Province,City,SampleDetails,BioProject,BioSample
0,Bat1,Artibeus lituratus,2007-10-05 00:00:00,Brazil,Sao Paulo,Valparaiso,Kidney,PRJNA557656,SAMN12405593
1,Bat2,Carollia perspicillata,2007-10-19 00:00:00,Brazil,Sao Paulo,Aracatuba,Liver,PRJNA557656,SAMN12405594
2,Bat3,Carollia perspicillata,2007-10-19 00:00:00,Brazil,Sao Paulo,Aracatuba,Kidney,PRJNA557656,SAMN12405595
3,Bat4,Glossophaga soricina,2007-10-19 00:00:00,Brazil,Sao Paulo,Aracatuba,Liver,PRJNA557656,SAMN12405596
4,Bat5,Glossophaga soricina,2007-10-19 00:00:00,Brazil,Sao Paulo,Aracatuba,Kidney,PRJNA557656,SAMN12405597
...,...,...,...,...,...,...,...,...,...
2967,Rt22QT161,Rhinolophus thomasi,2022-11-05 00:00:00,Vietnam,Quang Tri,ND,Feces,PRJNA1025946,SAMN37730889
2968,Rt22QT178,Rhinolophus thomasi,2022-11-05 00:00:00,Vietnam,Quang Tri,ND,Feces,PRJNA1025946,SAMN37730890
2969,Rt22QB8,Rhinolophus thomasi,2022-11-07 00:00:00,Vietnam,Quang Binh,ND,Feces,PRJNA1025946,SAMN37730872
2970,Rt22QB78,Rhinolophus thomasi,2022-11-10 00:00:00,Vietnam,Quang Binh,ND,Feces,PRJNA1025946,SAMN37730871
2971,Table saved from ZOVER [Wed Apr 01 2026],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df_our = pd.read_csv('latest_SRA_6569.csv', index_col=False)
df_our

D:\Users\User\AppData\Local\Temp\ipykernel_11452\1657131637.py:1: DtypeWarning: Columns (0: Location_Province, 1: ArrayExpress-SPECIES, 2: common_name, 3: ENA-FIRST-PUBLIC, 4: ENA-LAST-UPDATE, 5: external_id, 6: INSDC_first_public, 7: INSDC_last_update, 8: sample_description, 9: Sample_Barcode, 10: ref_biomaterial, 11: collected_by, 12: Broker_name, 13: env_biome, 14: env_feature, 15: env_material, 16: Biological_Replicate, 17: host_scientific_name, 18: lab_host, 19: specimen_voucher, 20: expected_source, 21: host_body_product, 22: host_tot_mass, 23: manuscript_id, 24: samp_capt_status, 25: samp_collect_device, 26: fasta_file (run), 27: sample_type, 28: sex, 29: BREED, 30: Cultivar, 31: dev_stage, 32: ecotype, 33: sub_species, 34: samp_size, 35: Library_ID, 36: rel_to_oxygen, 37: Detail_ID, 38: replicate, 39: SUBMISSION_TOOL (exp), 40: SUBMISSION_TOOL (run), 41: submission_tool, 42: SUBMISSION_TOOL_VERSION (exp), 43: SUBMISSION_TOOL_VERSION (run), 44: SUBMISSION_TOOL_VERSION, 45: genbank_accession, 46: sequencing_approach, 47: matrix_type, 48: organism_spiked_and_spike_in_level, 49: virus_enrich_app, 50: experimental_factor, 51: sample_ID, 52: specific_host, 53: additional_component_added_to_sample, 54: altitude, 55: BIOME, 56: env_package, 57: feature, 58: Investigation_type, 59: Label, 60: material, 61: sample_comment, 62: spike_in_level_of_influenza_a_virus) have mixed types. Specify dtype option on import or set low_memory=False.
  df_our = pd.read_csv('latest_SRA_6569.csv', index_col=False)

,Run,Assay Type,AvgSpotLen,Bases,BioSample,Bytes,Center Name,Consent,DATASTORE filetype,DATASTORE provider,...,additional_component_added_to_sample,altitude,BIOME,env_package,feature,Investigation_type,Label,material,sample_comment,spike_in_level_of_influenza_a_virus
0,SRR27491126,AMPLICON,300,3796245900,SAMN39397543,2388715895,INSTITUT PASTEUR OF SHANGHAI,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SRR27491127,AMPLICON,300,2721147000,SAMN39397542,1707201651,INSTITUT PASTEUR OF SHANGHAI,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SRR27491128,AMPLICON,300,4709894100,SAMN39397541,2950874629,INSTITUT PASTEUR OF SHANGHAI,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SRR27491129,AMPLICON,300,4779211500,SAMN39397540,3015086016,INSTITUT PASTEUR OF SHANGHAI,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SRR27491130,AMPLICON,300,5456230500,SAMN39397539,3394419299,INSTITUT PASTEUR OF SHANGHAI,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6564,ERR15951191,WGS,212,10740246317,SAMEA120589881,3365993450,QUADRAM INSTITUTE BIOSCIENCE,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6565,ERR15951193,WGS,280,59183488003,SAMEA120589883,17798921408,QUADRAM INSTITUTE BIOSCIENCE,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6566,ERR15951194,WGS,271,35140445635,SAMEA120589884,10911327171,QUADRAM INSTITUTE BIOSCIENCE,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6567,ERR15951203,WGS,274,6685169405,SAMEA120589893,2044166040,QUADRAM INSTITUTE BIOSCIENCE,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6568,SRR36330079,RNA-Seq,265,20195,SAMN53697127,92144,FEDERAL UNIVERSITY OF SAO PAULO,public,"bam,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
import pandas as pd


with open('projects_to_remove.txt', 'r') as f:
    projects_to_remove = [line.strip() for line in f]

df_filtered = df_our[~df_our['BioProject'].isin(projects_to_remove)]

df_filtered.to_csv('filtered_table.csv', index=False)

In [6]:
df_our = pd.read_csv('SRA_archives_final.csv', index_col=False)

D:\Users\User\AppData\Local\Temp\ipykernel_11452\2613667729.py:1: DtypeWarning: Columns (0: source_material_id, 1: Location_Province, 2: ArrayExpress-SPECIES, 3: common_name, 4: ENA-FIRST-PUBLIC, 5: ENA-LAST-UPDATE, 6: external_id, 7: INSDC_first_public, 8: INSDC_last_update, 9: sample_description, 10: Sample_Barcode, 11: ref_biomaterial, 12: collected_by, 13: tissue, 14: Broker_name, 15: env_biome, 16: env_feature, 17: env_material, 18: Biological_Replicate, 19: host_scientific_name, 20: lab_host, 21: specimen_voucher, 22: host_body_product, 23: host_tot_mass, 24: samp_capt_status, 25: samp_collect_device, 26: fasta_file (run), 27: sample_type, 28: sex, 29: BREED, 30: Cultivar, 31: dev_stage, 32: ecotype, 33: sub_species, 34: samp_size, 35: Library_ID, 36: rel_to_oxygen, 37: replicate, 38: SUBMISSION_TOOL (exp), 39: SUBMISSION_TOOL (run), 40: submission_tool, 41: SUBMISSION_TOOL_VERSION (exp), 42: SUBMISSION_TOOL_VERSION (run), 43: SUBMISSION_TOOL_VERSION, 44: genbank_accession, 45: sequencing_approach, 46: virus_enrich_app, 47: experimental_factor, 48: sample_ID, 49: specific_host, 50: altitude, 51: BIOME, 52: env_package, 53: feature, 54: Investigation_type, 55: Label, 56: material, 57: sample_comment) have mixed types. Specify dtype option on import or set low_memory=False.
  df_our = pd.read_csv('SRA_archives_final.csv', index_col=False)

In [9]:
matching_rows = df_our[df_our['BioSample'].isin(df_zover['BioSample'])]
matching_rows

,Run,Assay Type,AvgSpotLen,Bases,BioSample,Bytes,Center Name,Consent,DATASTORE filetype,DATASTORE provider,...,additional_component_added_to_sample,altitude,BIOME,env_package,feature,Investigation_type,Label,material,sample_comment,spike_in_level_of_influenza_a_virus
95,SRR27912327,WGS,298,3085496470,SAMN39879846,1259025954,UNIVERSITAT DE VALENCIA,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,SRR27912328,WGS,298,3272640768,SAMN39879845,1315849459,UNIVERSITAT DE VALENCIA,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,SRR27912329,WGS,276,1351361039,SAMN39879844,780573312,UNIVERSITAT DE VALENCIA,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,SRR27912330,WGS,298,4386745356,SAMN39879843,1906501423,UNIVERSITAT DE VALENCIA,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,SRR27912331,WGS,298,3616133150,SAMN39879842,1576038134,UNIVERSITAT DE VALENCIA,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4662,SRR28251003,RNA-Seq,298,7397556171,SAMN40258855,4697649447,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4663,SRR28251004,RNA-Seq,299,1417736932,SAMN40258854,918749601,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4664,SRR28251005,RNA-Seq,299,1257774019,SAMN40258853,808112824,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4665,SRR28251006,RNA-Seq,298,3507101388,SAMN40258852,2187692259,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4666,SRR28251010,RNA-Seq,298,9478727499,SAMN40259160,5998889224,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
matching_rows.to_csv('matching.csv')

In [6]:
not_matching_rows = df_our[~df_our['BioSample'].isin(df_zover['BioSample'])]
not_matching_rows['Collection_Date'].value_counts().to_csv('not_matched_dates.csv')

In [30]:
not_matching_rows.to_csv('not_matching.csv')

In [7]:
df_matches = pd.DataFrame()

In [8]:
df_matches['Matches'] = df_our['BioSample'].isin(df_zover['BioSample'])

In [9]:
df_matches['Project'] = df_our['BioProject'].isin(df_zover['BioProject'])

In [11]:
df_matches['Project'].value_counts()

Project
False    4839
True     1730
Name: count, dtype: int64

In [5]:
df_zover = pd.read_excel('ZOVER_bat_astroviruses.xlsx', header=1)
df_zover

,SampleName,Host,CollectionDate,Country,Province,City,SampleDetails,BioProject,BioSample
0,KSA_0412,Eidolon helvum,2012-10~2013-04,Saudi Arabia,Asir,Bisha,Rectal swab/fecal pellet,PRJNA487099,SAMN09873731
1,KSA_0430,unclassified Chiroptera,2012-10~2013-04,Saudi Arabia,Asir,Bisha,Rectal swab/fecal pellet,PRJNA487099,SAMN09873749
2,KSA_0435,Taphozous perforatus,2012-10~2013-04,Saudi Arabia,Asir,Bisha,Rectal swab/fecal pellet,PRJNA487099,SAMN09873753
3,130415_lane8,Miniopterus fuliginosus,2013,China,Guangdong,ND,Pharyngeal and anal swab,PRJNA171017,SAMN03761340
4,130601_lane8,Myotis ricketti,2013,China,Guangdong,ND,Pharyngeal and anal swab,PRJNA171017,SAMN03761350
...,...,...,...,...,...,...,...,...,...
149,L173.18,Myotis pilosus,2022-08,China,Guizhou,ND,Rectum,PRJNA901878,SAMN32394997
150,L177.18,Ia io,2022-08,China,Guizhou,ND,Rectum,PRJNA901878,SAMN32395001
151,P11,Myotis daubentonii,2022-08-03~2022-08-17,Spain,Lugo/Salamanca,Rabade/Navarredonda de la Rinconada,Feces,PRJNA1074704,SAMN39879841
152,Ra22QT106,Rhinolophus affinis,2022-11-03 00:00:00,Vietnam,Quang Tri,ND,Feces,PRJNA1025946,SAMN37730895
153,Table saved from ZOVER [Tue Apr 07 2026],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
matching_rows = df_our[df_our['BioSample'].isin(df_zover['BioSample'])]
matching_rows

,Run,Assay Type,AvgSpotLen,Bases,BioSample,Bytes,Center Name,Consent,DATASTORE filetype,DATASTORE provider,...,additional_component_added_to_sample,altitude,BIOME,env_package,feature,Investigation_type,Label,material,sample_comment,spike_in_level_of_influenza_a_virus
100,SRR27912332,WGS,298,1791628746,SAMN39879841,756283095,UNIVERSITAT DE VALENCIA,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,SRR22936602,WGS,300,12457547100,SAMN32394822,3967403963,SOUTH CHINA AGRICULTURAL UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,SRR22936710,WGS,300,12308733300,SAMN32394898,4015418116,SOUTH CHINA AGRICULTURAL UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,SRR22936796,WGS,300,32661453600,SAMN32394997,10730387949,SOUTH CHINA AGRICULTURAL UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,SRR22936808,WGS,300,22326472500,SAMN32394986,7399477101,SOUTH CHINA AGRICULTURAL UNIVERSITY,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4538,SRR28250713,RNA-Seq,295,14969290933,SAMN40259440,9899035905,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4617,SRR28250862,RNA-Seq,297,628042915,SAMN40258967,394929857,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4643,SRR28250888,RNA-Seq,299,8446609858,SAMN40258880,5532514188,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4699,SRR28250944,RNA-Seq,296,1660832541,SAMN40259089,1055677929,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4725,SRR28250970,RNA-Seq,297,8606908315,SAMN40259126,5418286293,BGI RESEARCH,public,"fastq,run.zq,sra","gs,ncbi,s3",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN